import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { fetchInstances } from "../entities/instances/api";
import type { ReportInstance } from "../entities/instances/types";
import { createTask, fetchTasks, pauseTask, resumeTask, runTaskNow } from "../entities/tasks/api";
import type { ScheduledTaskCreatePayload } from "../entities/tasks/types";
import { fetchTemplates } from "../entities/templates/api";
import { ListPageLayout } from "../shared/layouts/ListPageLayout";
import { PageIntroBar } from "../shared/layouts/PageIntroBar";
import { formatDateTime } from "../shared/utils/format";
import { EmptyState } from "../shared/ui/EmptyState";
import { PageSection } from "../shared/ui/PageSection";
import { StatusBanner } from "../shared/ui/StatusBanner";
import { SurfaceCard } from "../shared/ui/SurfaceCard";

type TaskFormState = {
  name: string;
  description: string;
  sourceInstanceId: string;
  scheduleType: "once" | "recurring";
  cronExpression: string;
  autoGenerateDoc: boolean;
  timeParamName: string;
  timeFormat: string;
  useScheduleTimeAsReportTime: boolean;
};

function createInitialTaskForm(): TaskFormState {
  return {
    name: "",
    description: "",
    sourceInstanceId: "",
    scheduleType: "recurring",
    cronExpression: "",
    autoGenerateDoc: true,
    timeParamName: "date",
    timeFormat: "%Y-%m-%d",
    useScheduleTimeAsReportTime: false,
  };
}

export function TasksPage() {
  const queryClient = useQueryClient();
  const [message, setMessage] = useState("");
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [form, setForm] = useState<TaskFormState>(createInitialTaskForm());

  const tasksQuery = useQuery({
    queryKey: ["tasks"],
    queryFn: fetchTasks,
  });
  const templatesQuery = useQuery({
    queryKey: ["templates"],
    queryFn: fetchTemplates,
  });
  const instancesQuery = useQuery({
    queryKey: ["instances"],
    queryFn: fetchInstances,
  });

  const templateNameMap = useMemo(
    () => new Map((templatesQuery.data ?? []).map((item) => [item.template_id, item.name])),
    [templatesQuery.data],
  );
  const instanceMap = useMemo(
    () => new Map((instancesQuery.data ?? []).map((item) => [item.instance_id, item])),
    [instancesQuery.data],
  );
  const selectedSourceInstance = form.sourceInstanceId ? instanceMap.get(form.sourceInstanceId) ?? null : null;

  const actionMutation = useMutation({
    mutationFn: async ({ taskId, action }: { taskId: string; action: "run" | "pause" | "resume" }) => {
      if (action === "run") {
        return runTaskNow(taskId);
      }
      if (action === "pause") {
        return pauseTask(taskId);
      }
      return resumeTask(taskId);
    },
    onSuccess: async (result) => {
      setMessage(typeof result?.message === "string" ? result.message : "任务操作已执行。");
      await queryClient.invalidateQueries({ queryKey: ["tasks"] });
    },
    onError: (error) => {
      setMessage(error instanceof Error ? error.message : "任务操作失败。");
    },
  });

  const createMutation = useMutation({
    mutationFn: (payload: ScheduledTaskCreatePayload) => createTask(payload),
    onSuccess: async () => {
      setMessage("定时任务已创建。");
      setIsCreateOpen(false);
      setForm(createInitialTaskForm());
      await queryClient.invalidateQueries({ queryKey: ["tasks"] });
    },
    onError: (error) => {
      setMessage(error instanceof Error ? error.message : "定时任务创建失败。");
    },
  });

  function updateForm<K extends keyof TaskFormState>(field: K, value: TaskFormState[K]) {
    setForm((current) => ({
      ...current,
      [field]: value,
    }));
  }

  function openCreateDialog() {
    setForm(createInitialTaskForm());
    setIsCreateOpen(true);
  }

  function submitCreateTask() {
    if (!selectedSourceInstance) {
      setMessage("请选择源报告实例。");
      return;
    }
    const payload: ScheduledTaskCreatePayload = {
      name: form.name.trim(),
      description: form.description.trim(),
      source_instance_id: selectedSourceInstance.instance_id,
      template_id: selectedSourceInstance.template_id,
      schedule_type: form.scheduleType,
      cron_expression: form.cronExpression.trim(),
      auto_generate_doc: form.autoGenerateDoc,
      time_param_name: form.timeParamName.trim(),
      time_format: form.timeFormat.trim(),
      use_schedule_time_as_report_time: form.useScheduleTimeAsReportTime,
    };
    createMutation.mutate(payload);
  }

  return (
    <div className="tasks-page">
      <PageSection description="查看任务状态，并直接执行运行、暂停和恢复。">
        {message ? (
          <StatusBanner tone="info" title="任务反馈">
            {message}
          </StatusBanner>
        ) : null}

        <ListPageLayout
          intro={
            <PageIntroBar
              eyebrow="Scheduled Tasks"
              description="统一查看任务运行情况，并从已有报告实例创建新的定时任务。"
              badge={`${tasksQuery.data?.length ?? 0} 个任务`}
              actions={
                <button className="primary-button" type="button" onClick={openCreateDialog}>
                  新建任务
                </button>
              }
            />
          }
          content={
            <SurfaceCard>
              <div className="table-shell">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>任务名称</th>
                      <th>模板</th>
                      <th>状态</th>
                      <th>最近运行</th>
                      <th>执行情况</th>
                      <th>操作</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(tasksQuery.data ?? []).map((task) => (
                      <tr key={task.task_id}>
                        <td>{task.name}</td>
                        <td>{templateNameMap.get(task.template_id) ?? task.template_id}</td>
                        <td>{task.status}</td>
                        <td>{formatDateTime(task.last_run_at)}</td>
                        <td>
                          {task.success_runs}/{task.total_runs}
                        </td>
                        <td>
                          <div className="action-row action-row--compact">
                            <button
                              className="secondary-button"
                              type="button"
                              onClick={() => actionMutation.mutate({ taskId: task.task_id, action: "run" })}
                            >
                              立即运行
                            </button>
                            {task.enabled ? (
                              <button
                                className="ghost-button ghost-button--inline"
                                type="button"
                                onClick={() => actionMutation.mutate({ taskId: task.task_id, action: "pause" })}
                              >
                                暂停
                              </button>
                            ) : (
                              <button
                                className="ghost-button ghost-button--inline"
                                type="button"
                                onClick={() => actionMutation.mutate({ taskId: task.task_id, action: "resume" })}
                              >
                                恢复
                              </button>
                            )}
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                {!tasksQuery.data?.length && !tasksQuery.isLoading ? (
                  <EmptyState title="暂无定时任务" description="点击右上角“新建任务”即可从现有报告实例创建。" />
                ) : null}
              </div>
            </SurfaceCard>
          }
        />

        {isCreateOpen ? (
          <div className="modal-backdrop" role="presentation" onClick={() => setIsCreateOpen(false)}>
            <div
              className="modal-panel"
              role="dialog"
              aria-modal="true"
              aria-labelledby="create-task-title"
              onClick={(event) => event.stopPropagation()}
            >
              <div className="list-header">
                <div>
                  <p className="section-kicker">Scheduled Tasks</p>
                  <h3 id="create-task-title">新建定时任务</h3>
                </div>
                <button className="ghost-button ghost-button--inline" type="button" onClick={() => setIsCreateOpen(false)}>
                  关闭
                </button>
              </div>

              <div className="form-grid">
                <label className="field">
                  <span className="field-label">任务名称</span>
                  <input aria-label="任务名称" value={form.name} onChange={(event) => updateForm("name", event.target.value)} />
                </label>
                <label className="field">
                  <span className="field-label">调度方式</span>
                  <select aria-label="调度方式" value={form.scheduleType} onChange={(event) => updateForm("scheduleType", event.target.value as "once" | "recurring")}>
                    <option value="once">一次性</option>
                    <option value="recurring">周期性</option>
                  </select>
                </label>
                <label className="field field--full">
                  <span className="field-label">说明</span>
                  <textarea aria-label="说明" rows={3} value={form.description} onChange={(event) => updateForm("description", event.target.value)} />
                </label>
                <label className="field field--full">
                  <span className="field-label">源报告实例</span>
                  <select aria-label="源报告实例" value={form.sourceInstanceId} onChange={(event) => updateForm("sourceInstanceId", event.target.value)}>
                    <option value="">请选择实例</option>
                    {(instancesQuery.data ?? []).map((instance: ReportInstance) => (
                      <option key={instance.instance_id} value={instance.instance_id}>
                        {instance.instance_id} · {templateNameMap.get(instance.template_id) ?? instance.template_id}
                      </option>
                    ))}
                  </select>
                </label>
                <label className="field field--full">
                  <span className="field-label">Cron 表达式</span>
                  <input aria-label="Cron 表达式" value={form.cronExpression} onChange={(event) => updateForm("cronExpression", event.target.value)} />
                </label>
                <label className="field">
                  <span className="field-label">时间参数名</span>
                  <input aria-label="时间参数名" value={form.timeParamName} onChange={(event) => updateForm("timeParamName", event.target.value)} />
                </label>
                <label className="field">
                  <span className="field-label">时间格式</span>
                  <input value={form.timeFormat} onChange={(event) => updateForm("timeFormat", event.target.value)} />
                </label>
                <label className="field field--checkbox">
                  <span className="field-label">自动生成文档</span>
                  <label className="choice-chip active">
                    <input type="checkbox" checked={form.autoGenerateDoc} onChange={(event) => updateForm("autoGenerateDoc", event.target.checked)} />
                    <span>执行后自动输出 Markdown</span>
                  </label>
                </label>
                <label className="field field--checkbox">
                  <span className="field-label">时间映射</span>
                  <label className="choice-chip active">
                    <input type="checkbox" checked={form.useScheduleTimeAsReportTime} onChange={(event) => updateForm("useScheduleTimeAsReportTime", event.target.checked)} aria-label="执行时间写入报告时间" />
                    <span>执行时间写入报告时间</span>
                  </label>
                </label>
              </div>

              {selectedSourceInstance ? (
                <p className="muted-text">将自动使用模板：{templateNameMap.get(selectedSourceInstance.template_id) ?? selectedSourceInstance.template_id}</p>
              ) : null}

              <div className="action-row">
                <button
                  className="primary-button"
                  type="button"
                  onClick={submitCreateTask}
                  disabled={!form.name.trim() || !selectedSourceInstance || createMutation.isPending}
                >
                  {createMutation.isPending ? "创建中..." : "创建任务"}
                </button>
              </div>
            </div>
          </div>
        ) : null}
      </PageSection>
    </div>
  );
}
