"""Report application-owned interfaces implemented by infrastructure adapters."""

from __future__ import annotations

from typing import Any, Protocol

from ..domain.generation_models import DocumentArtifact, ReportDsl
from ..domain.template_models import ParameterValue
from .generation_models import DocumentView, DownloadResolution, GeneratedArtifact


class ParameterOptionsResolver(Protocol):
    def resolve(self, *, source: str, request_payload: dict[str, list[dict[str, Any]]], user_id: str) -> dict[str, Any]: ...


class ReportSchemaValidator(Protocol):
    def validate_template_instance(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def validate_report(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def validate_catalog(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def validate_section(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def validate_slide(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def validate_components(self, payload: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
    def validate_onequery_response(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def validate_api_dataset_response(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def validate_dynamic_custom_response(self, payload: dict[str, Any]) -> dict[str, Any]: ...


class DatasetQueryGateway(Protocol):
    def execute_sql(self, *, query: str, context: dict[str, Any], user_id: str): ...
    def execute_api(self, *, source: str, payload: dict[str, Any], user_id: str): ...


class ReportReader(Protocol):
    def get_report_instance(self, report_id: str, *, user_id: str): ...


class DocumentExportGateway(Protocol):
    def generate_document(
        self,
        *,
        report: ReportDsl,
        report_id: str,
        format_name: str,
        theme: str,
        strict_validation: bool,
        pdf_source: str | None,
    ) -> GeneratedArtifact: ...

    def resolve_download(self, document: DocumentArtifact) -> DownloadResolution: ...
    def serialize_document(self, document: DocumentArtifact) -> DocumentView: ...
