import os
import unittest


class FrontendChatRenderTests(unittest.TestCase):
    def test_ask_param_render_shows_template_and_date_input(self):
        base = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
        panel_path = os.path.join(base, "frontend", "src", "features", "chat-report-flow", "components", "ChatActionPanel.tsx")
        with open(panel_path, "r", encoding="utf-8") as f:
            content = f.read()
        self.assertIn("已匹配模板", content)
        self.assertIn('action.widget.kind === "date"', content)

    def test_review_params_render_supports_confirm_reset_and_edit(self):
        base = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
        panel_path = os.path.join(base, "frontend", "src", "features", "chat-report-flow", "components", "ChatActionPanel.tsx")
        with open(panel_path, "r", encoding="utf-8") as f:
            content = f.read()
        self.assertIn('action.type === "review_params"', content)
        self.assertIn("prepare_outline_review", content)
        self.assertIn("reset_params", content)
        self.assertIn("edit_param", content)
        self.assertIn('action.type === "review_outline"', content)
        self.assertIn("confirm_outline_generation", content)
        self.assertIn("edit_outline", content)
        self.assertIn("display_text", content)
        self.assertIn("ai_generated", content)
        self.assertIn("node_kind", content)
        self.assertNotIn("章节标题", content)
        self.assertNotIn("章节说明", content)

    def test_frontend_supports_structured_param_widgets_and_v2_schema(self):
        base = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
        chat_page_path = os.path.join(base, "frontend", "src", "pages", "ChatPage.tsx")
        template_catalog_path = os.path.join(base, "frontend", "src", "pages", "TemplatesPage.tsx")
        template_instances_path = os.path.join(base, "frontend", "src", "pages", "TemplateInstancesPage.tsx")
        template_detail_path = os.path.join(base, "frontend", "src", "pages", "TemplateDetailPage.tsx")
        navigation_path = os.path.join(base, "frontend", "src", "shared", "navigation.ts")
        workbench_path = os.path.join(base, "frontend", "src", "features", "template-workbench", "TemplateWorkbench.tsx")
        workbench_css_path = os.path.join(base, "frontend", "src", "features", "template-workbench", "templateWorkbench.css")
        panel_path = os.path.join(base, "frontend", "src", "features", "chat-report-flow", "components", "ChatActionPanel.tsx")
        with open(chat_page_path, "r", encoding="utf-8") as f:
            chat_content = f.read()
        with open(template_catalog_path, "r", encoding="utf-8") as f:
            template_catalog_content = f.read()
        with open(template_instances_path, "r", encoding="utf-8") as f:
            template_instances_content = f.read()
        with open(template_detail_path, "r", encoding="utf-8") as f:
            template_detail_content = f.read()
        with open(navigation_path, "r", encoding="utf-8") as f:
            navigation_content = f.read()
        with open(workbench_path, "r", encoding="utf-8") as f:
            workbench_content = f.read()
        with open(workbench_css_path, "r", encoding="utf-8") as f:
            workbench_styles = f.read()
        with open(panel_path, "r", encoding="utf-8") as f:
            panel_content = f.read()
        self.assertIn("param_values", chat_content)
        self.assertIn("outline_override", chat_content)
        self.assertIn("forkChatSession", chat_content)
        self.assertIn("session_id\") ?? \"\"", chat_content)
        self.assertIn("Fork 来源", chat_content)
        self.assertIn("更多操作：消息", chat_content)
        self.assertIn("Fork 为新会话", chat_content)
        self.assertIn("更多操作", chat_content)
        self.assertIn("重命名（暂未开放）", chat_content)
        self.assertIn("chat-send-button", chat_content)
        self.assertIn("message-bubble--pending", chat_content)
        self.assertIn("message-entry__role", chat_content)
        self.assertIn("message-entry__body--compact", chat_content)
        self.assertIn("message-entry__body--has-action", chat_content)
        self.assertIn("message-entry__time", chat_content)
        self.assertIn("created_at", chat_content)
        self.assertNotIn("message-bubble__meta", chat_content)
        self.assertNotIn("默认工作区", chat_content)
        self.assertNotIn("发送中...", chat_content)
        self.assertNotIn("支持直接输入自然语言需求", chat_content)
        self.assertIn("multi_select", panel_content)
        self.assertIn("single_select", panel_content)
        self.assertIn("review_outline", panel_content)
        self.assertIn("保存大纲", panel_content)
        self.assertIn("outline-tree", panel_content)
        self.assertIn("编辑章节", panel_content)
        self.assertIn("outline-tree__toggle", panel_content)
        self.assertIn('"展开" : "折叠"', panel_content)
        self.assertIn("AI", panel_content)
        self.assertIn("/templates/new", template_catalog_content)
        self.assertIn("模板实例", navigation_content)
        self.assertIn("/template-instances", navigation_content)
        self.assertIn("outline_preview", template_instances_content)
        self.assertIn("capture_stage", template_instances_content)
        self.assertIn("Fork 到对话助手", template_instances_content)
        self.assertIn("schemaVersion", template_detail_content)
        self.assertIn("TemplateWorkbench", template_detail_content)
        self.assertIn("预览示例值", workbench_content)
        self.assertIn("数据准备", workbench_content)
        self.assertIn("模板 JSON", workbench_content)
        self.assertIn("template-workbench__parameters", workbench_content)
        self.assertNotIn("<h3>兼容迁移</h3>", workbench_content)
        self.assertIn("grid-template-columns: minmax(220px, 0.8fr) 1px minmax(0, 1.4fr);", workbench_styles)
        self.assertIn(".workbench-split::before {", workbench_styles)

    def test_chat_styles_keep_message_stream_balanced(self):
        base = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
        pages_css_path = os.path.join(base, "frontend", "src", "styles", "pages.css")
        with open(pages_css_path, "r", encoding="utf-8") as f:
            styles = f.read()
        self.assertIn(".message-list {\n  display: flex;", styles)
        self.assertIn(".message-entry {", styles)
        self.assertIn(".message-entry__role {", styles)
        self.assertIn(".message-entry__time {", styles)
        self.assertIn(".message-entry__menu-wrap {", styles)
        self.assertIn(".message-entry__menu-trigger {", styles)
        self.assertIn(".message-entry__menu {", styles)
        self.assertIn(".message-entry--assistant .message-entry__time {", styles)
        self.assertIn(".message-entry--user .message-entry__role {", styles)
        self.assertIn("inline-size: 75%;", styles)
        self.assertIn("max-inline-size: 75%;", styles)
        self.assertIn(".message-entry--user .message-entry__body {\n  width: fit-content;\n  max-inline-size: 40%;\n}", styles)
        self.assertIn(".message-entry__body--compact {\n  width: fit-content;\n  max-inline-size: 40%;\n}", styles)
        self.assertIn(".message-entry__body--has-action {\n  max-inline-size: 60%;\n}", styles)
        self.assertIn(".message-bubble--user {\n  inline-size: fit-content;", styles)
        self.assertIn("inline-size: 100%;", styles)
        self.assertIn("flex-direction: column;", styles)
        self.assertIn("min-height: 320px", styles)
        self.assertIn("min-height: 64px", styles)
        self.assertIn(".chat-compose-dock {", styles)
        self.assertIn("position: fixed;", styles)
        self.assertIn(".chat-compose {\n  display: grid;\n  grid-template-columns: minmax(0, 1fr) auto;", styles)
        self.assertIn(".chat-compose textarea {\n  grid-column: 1;", styles)
        self.assertIn(".chat-send-button {\n  grid-column: 2;", styles)
        self.assertIn(".chat-send-button {", styles)
        self.assertIn(".chat-send-button.is-pending .chat-send-button__glyph {", styles)
        self.assertIn(".chat-stream-card:hover {", styles)
        self.assertIn(".message-bubble--pending {", styles)
        self.assertIn(".chat-stream-shell {", styles)
        self.assertIn(".chat-page__shell {\n  position: relative;", styles)
        self.assertIn("gap: 0;", styles)
        self.assertIn(".chat-history-rail {", styles)
        self.assertIn(".chat-history-panel {\n  position: fixed;", styles)
        self.assertIn("left: var(--chat-history-left);", styles)
        self.assertIn("width: var(--chat-history-width);", styles)
        self.assertIn("height: var(--chat-history-height);", styles)
        self.assertIn("overflow: hidden;", styles)
        self.assertIn(".chat-history-panel__body {\n  display: flex;\n  flex: 1 1 auto;\n  min-height: 0;\n  overflow-y: auto;", styles)
        self.assertIn(".chat-page__shell.is-history-collapsed {\n  grid-template-columns: 36px minmax(0, 1fr);\n}", styles)
        self.assertIn(".chat-history-panel__divider-toggle {", styles)
        self.assertIn("top: 50%;", styles)
        self.assertIn("transform: translateY(-50%);", styles)
        self.assertIn("inline-size: 32px;", styles)
        self.assertIn("block-size: 40px;", styles)
        self.assertIn(".chat-history-item.is-active {\n  background: rgba(37, 109, 130, 0.08);\n}", styles)
        self.assertIn(".chat-history-item__menu-trigger {", styles)
        self.assertIn(".chat-history-item__menu {", styles)
        self.assertIn(".chat-history-item__main strong {", styles)
        self.assertIn("padding-bottom: var(--chat-compose-reserve, 176px);", styles)
        self.assertIn(".chat-compose-dock {\n  position: fixed;", styles)
        self.assertIn("padding: 0;", styles)
        self.assertIn("background: transparent;", styles)
        self.assertIn("box-shadow: none;", styles)
        self.assertNotIn("padding: 0 0 8px;", styles)
        self.assertNotIn(".message-bubble__meta {", styles)
        self.assertIn(".outline-tree {", styles)
        self.assertIn(".outline-tree__label {", styles)
        self.assertIn(".outline-tree__toolbar {", styles)
        self.assertIn(".outline-tree__node:hover .outline-tree__toolbar", styles)

    def test_shared_layouts_no_longer_cap_page_widths(self):
        base = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
        layout_css_path = os.path.join(base, "frontend", "src", "styles", "layout.css")
        app_shell_path = os.path.join(base, "frontend", "src", "app", "shell", "AppShell.tsx")
        with open(layout_css_path, "r", encoding="utf-8") as f:
            styles = f.read()
        with open(app_shell_path, "r", encoding="utf-8") as f:
            shell_content = f.read()
        self.assertNotIn("max-width: 1180px", styles)
        self.assertNotIn("max-width: 1220px", styles)
        self.assertNotIn("max-width: 1040px", styles)
        self.assertIn(".app-sidebar {\n  position: sticky;", styles)
        self.assertIn(".app-header__actions {", styles)
        self.assertIn(".header-feedback-link {", styles)
        self.assertIn(".header-feedback-link__icon {", styles)
        self.assertIn("app-header__actions", shell_content)
        self.assertIn("header-feedback-link", shell_content)
        self.assertIn("header-feedback-link__icon", shell_content)
        self.assertNotIn("默认工作区", shell_content)

    def test_settings_page_uses_inline_action_feedback(self):
        base = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
        settings_page_path = os.path.join(base, "frontend", "src", "pages", "SettingsPage.tsx")
        pages_css_path = os.path.join(base, "frontend", "src", "styles", "pages.css")
        with open(settings_page_path, "r", encoding="utf-8") as f:
            settings_content = f.read()
        with open(pages_css_path, "r", encoding="utf-8") as f:
            styles = f.read()
        self.assertNotIn('title="操作反馈"', settings_content)
        self.assertIn("settings-action-feedback", settings_content)
        self.assertIn(".settings-action-feedback {", styles)


if __name__ == "__main__":
    unittest.main()

